# Generated by Django 4.2.9 on 2024-02-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('good', models.IntegerField(default=0)),
                ('bad', models.IntegerField(default=0)),
            ],
        ),
    ]
