# Generated by Django 4.2.9 on 2024-02-06 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoreview',
            name='last_reset_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
