# Generated by Django 4.2.9 on 2024-02-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_favoriteusercryptocurrency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteusercryptocurrency',
            old_name='cryptocurrency_symbol',
            new_name='favorite_crypto_symbol',
        ),
        migrations.AlterUniqueTogether(
            name='favoriteusercryptocurrency',
            unique_together={('user', 'favorite_crypto_symbol')},
        ),
    ]
