# Generated by Django 4.2.9 on 2024-02-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_cryptocurrency_symbol_favoriteusercryptocurrency_favorite_crypto_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pesel',
            field=models.CharField(max_length=11),
        ),
    ]
